name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip

      - name: Auth Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Enable RDP Firewall
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Enable RDP User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Admin Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Download TigerVNC
        run: |
          $url = "https://downloads.sourceforge.net/project/tigervnc/stable/1.13.1/TigerVNC-1.13.1.exe"
          $output = "tigervnc.exe"
          $attempts = 3
          while ($attempts -gt 0) {
              Invoke-WebRequest -Uri $url -OutFile $output
              if ((Test-Path $output) -and ((Get-Item $output).Length -gt 0)) { break }
              $attempts--
          }
          if ($attempts -eq 0) { throw "Failed to download TigerVNC after multiple attempts." }

      - name: Install TigerVNC
        run: Start-Process -Wait -FilePath .\tigervnc.exe -ArgumentList "/S"

      - name: Configure VNC Password
        run: |
          echo "password" | vncpasswd -f > C:\Users\runneradmin\.vnc\passwd
          Set-ItemProperty -Path 'HKLM:\Software\TigerVNC\Server' -Name "PasswordFile" -Value "C:\Users\runneradmin\.vnc\passwd"

      - name: Start VNC Server
        run: Start-Process -NoNewWindow -FilePath "C:\Program Files\TigerVNC\vncserver.exe" -ArgumentList ":1"

      - name: Create Ngrok Tunnel
        run: .\ngrok\ngrok.exe tcp 5901
