name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Install Chrome and Chrome Remote Desktop
      run: |
        brew install --cask google-chrome
        brew install --cask chrome-remote-desktop-host
        # Verify installation
        if ! [ -f "/opt/google/chrome-remote-desktop/start-host" ]; then
          echo "Chrome Remote Desktop installation failed or script not found."
          exit 1
        fi

    - name: Download and Extract ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
        unzip ngrok.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create runneradmin User
      run: sudo sysadminctl -addUser runneradmin -password P@ssw0rd! -admin

    - name: Start Chrome Remote Desktop
      run: |
        export DISPLAY=
        if [ -f "/opt/google/chrome-remote-desktop/start-host" ]; then
          /opt/google/chrome-remote-desktop/start-host \
            --code="4/0AeanS0YlZGEWmEyWPbxRAph-fTyumhtTCvYAK0_YK2bi6kjsltyhjJTefS32jjJuRZGezA" \
            --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
            --name=$(hostname)
        else
          echo "Chrome Remote Desktop start-host script not found."
          exit 1
        fi

    - name: Enable Screen Sharing and Remote Login
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on -privs -all -users runneradmin
        sudo systemsetup -setremotelogin on

    - name: Set Password
      run: sudo sysadminctl -adminUser admin -adminPassword adminpassword -resetPasswordFor runneradmin -newPassword P@ssw0rd!

    - name: Start ngrok Tunnel
      run: ./ngrok tcp 5900
