name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download
      run: curl -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
    
    - name: Extract
      run: unzip ngrok.zip
    
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Login
      run: sudo systemsetup -setremotelogin on
    
    - name: Allow SSH Access
      run: sudo dscl . append /Groups/com.apple.access_ssh GroupMembership $USER

    - name: Create Tunnel
      run: ./ngrok tcp 22
