name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up job
      run: echo Setting up...

    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath .

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set runneradmin password
      run: net user runneradmin P@ssw0rd!

    - name: Install Python (for noVNC utils)
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Download and install TigerVNC
      run: |
        Invoke-WebRequest https://downloads.sourceforge.net/project/tigervnc/stable/1.13.1/TigerVNC-1.13.1-64-bit.exe -OutFile C:\vnc_installer.exe
        Start-Process -FilePath "C:\vnc_installer.exe" -ArgumentList "/silent" -Wait

    - name: Start TigerVNC server
      run: |
        vncserver -passwd < NUL
        vncserver :1

    - name: Clone and start noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        Start-Process -FilePath "websockify\websockify.exe" -ArgumentList "6901", "localhost:5901" -NoNewWindow

    - name: Sleep to let VNC and noVNC start
      run: Start-Sleep -Seconds 10

    - name: Start ngrok HTTP (noVNC) in foreground
      run: Start-Process .\ngrok\ngrok.exe -ArgumentList "http", "6901" -NoNewWindow

    - name: Loop and print Ngrok URLs forever
      run: |
        while ($true) {
          Write-Host "======== NGROK TUNNELS ========"
          $response = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
          $response.tunnels | ForEach-Object {
            Write-Host "Name: $($_.name)"
            Write-Host "URL: $($_.public_url)"
          }
          Start-Sleep -Seconds 5
        }
