name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y sudo wget curl git x11vnc xvfb \
          kde-plasma-desktop firefox fluxbox net-tools

    - name: Set display and start X session
      run: |
        export DISPLAY=:1
        Xvfb :1 -screen 0 1024x768x24 &

    - name: Start KDE session and x11vnc
      run: |
        export DISPLAY=:1
        startplasma-x11 &
        sleep 10
        x11vnc -display :1 -nopw -forever -shared -bg

    - name: Clone and start noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        git clone https://github.com/novnc/websockify
        ./utils/launch.sh --vnc localhost:5900 --listen 6901 &

    - name: Install and run Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update && sudo apt-get install -y ngrok
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ngrok http 6901 &

    - name: Wait for services to start
      run: sleep 20

    - name: Continuously print Ngrok public URL
      run: |
        while true; do curl -s http://127.0.0.1:4040/api/tunnels | grep -Eo 'https://[a-z0-9]+\\.ngrok-free\\.app'; sleep 30; done
