name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath .

    - name: Authenticate ngrok
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Configure RDP User Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set Local User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start ngrok Tunnel
      run: |
        .\ngrok.exe tcp 3389 > ngrok_output.log &
        Start-Sleep -Seconds 15
        $ngrokOutput = Get-Content ngrok_output.log
        $ngrokUrl = $ngrokOutput | Select-String -Pattern "tcp://.*" | ForEach-Object { $_.Matches[0].Value }
        if (-not $ngrokUrl) {
          Write-Host "Failed to retrieve ngrok URL from logs."
          exit 1
        }
        Write-Host "ngrok public URL: $ngrokUrl"
        $ngrokUrl = $ngrokUrl.Replace("tcp://", "")
        Write-Host "ngrok public URL without tcp://: $ngrokUrl"

    - name: Keep alive for 6 hours
      run: |
        $endTime = (Get-Date).AddHours(6)
        while ((Get-Date) -lt $endTime) {
          Write-Host "Keeping the session alive..."
          Start-Sleep -Seconds 60 # Wait for a minute before printing again
        }
        Write-Host "The 6-hour period has ended."
