name: CI

on: [push, workflow_dispatch]

jobs:
  reemo-session:
    runs-on: windows-latest

    steps:
      - name: Generate Random VM Name
        run: |
          $vmName = "vm-" + ([System.Guid]::NewGuid().ToString().Substring(0, 8))
          echo "VM_NAME=$vmName" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Install Python and Firebase Admin
        run: |
          choco install -y python
          python -m pip install firebase-admin

      - name: (Mock) Install Reemo Agent
        run: |
          Invoke-WebRequest -Uri "https://reemo.io/download/windows" -OutFile "ReemoSetup.exe"
          echo "Reemo agent downloaded (registration not possible in GitHub VMs)."

      - name: Generate Mock Reemo Session ID
        run: |
          $sessionId = [System.Guid]::NewGuid().ToString()
          $deviceId = "mock-device-" + ([System.Guid]::NewGuid().ToString().Substring(0, 6))
          echo "SESSION_ID=$sessionId" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
          echo "DEVICE_ID=$deviceId" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Upload Session Info to Firebase (Inline Python)
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
          GITHUB_ID: ${{ github.actor }}
          VM_NAME: ${{ env.VM_NAME }}
          SESSION_ID: ${{ env.SESSION_ID }}
          DEVICE_ID: ${{ env.DEVICE_ID }}
        run: |
          echo "$env:FIREBASE_KEY" > creds.json

          $uploadScript = @"
import firebase_admin
from firebase_admin import credentials, firestore
import os

cred = credentials.Certificate("creds.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

doc_ref = db.collection("reemo_sessions").document(os.environ["GITHUB_ID"])
doc_ref.set({
    "github_id": os.environ["GITHUB_ID"],
    "vm_name": os.environ["VM_NAME"],
    "session_id": os.environ["SESSION_ID"],
    "device_id": os.environ["DEVICE_ID"]
})
"@

          $uploadScript | Out-File -Encoding utf8 upload_url.py
          python upload_url.py

      - name: Loop output of session info
        run: |
          while ($true) {
            echo "GitHub ID: ${{ github.actor }}"
            echo "VM Name: ${{ env.VM_NAME }}"
            echo "Session ID: ${{ env.SESSION_ID }}"
            echo "Device ID: ${{ env.DEVICE_ID }}"
            Start-Sleep -Seconds 10
          }
