name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install LXDE, VNC, and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lxde lxde-core lxterminal tigervnc-standalone-server
        mkdir -p ~/.vnc
        echo "P@ssw0rd!" | vncpasswd -f > ~/.vnc/passwd
        sudo chmod 600 ~/.vnc/passwd

    - name: Set LXDE as default session for VNC
      run: echo "lxsession -s LXDE -e LXDE" > ~/.vnc/xstartup

    - name: Start VNC server
      run: vncserver :1 -geometry 1280x800 -depth 24

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable VNC connections
      run: sudo ufw allow 5901/tcp

    - name: Provide VNC address
      run: |
        IP_ADDRESS=$(hostname -I)
        echo "VNC Server running at: ${IP_ADDRESS}:1"

    - name: Set VNC user password
      run: echo 'runneradmin:P@ssw0rd!' | sudo chpasswd

    - name: Create Tunnel
      run: ./ngrok tcp 5901
