name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Enable Remote Management and Screen Sharing
      run: |
        # Enable Remote Management
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
          -activate -configure -access -on -users runneradmin -privs -all
        # Enable Remote Login (SSH)
        sudo systemsetup -setremotelogin on
        # Verify Services
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -status

    - name: Set User Password
      run: sudo sysadminctl -addUser runneradmin -password P@ssw0rd! -admin

    - name: Download and Configure ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        # Start ngrok for VNC (Port 5900)
        ./ngrok authtoken $NGROK_AUTH_TOKEN
        ./ngrok tcp 5900 > ngrok.log &
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Output ngrok Tunnel Information
      run: |
        sleep 5  # Wait for ngrok to initialize
        cat ngrok.log | grep "tcp://" || echo "Ngrok tunnel not established."

    - name: Confirm macOS Remote Management Setup
      run: |
        echo "Testing connectivity..."
        netstat -an | grep 5900 || echo "VNC port not active. Ensure Remote Management is enabled."

    - name: Display Connection Details
      run: |
        echo "Access macOS GUI via VNC."
        echo "Use VNC client and connect to the ngrok tunnel address."

    - name: Keep Workflow Active for 10 Hours
      run: |
        echo "Keeping the workflow active for 10 hours."
        sleep $((10 * 3600))  # Sleep for 10 hours
