name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl unzip python3 python3-pip \
          xvfb fluxbox x11vnc net-tools nodejs npm jq

    - name: Download and install noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        git clone https://github.com/novnc/websockify.git
        npm install

    - name: Start virtual display and window manager
      run: |
        export DISPLAY=:1
        Xvfb :1 -screen 0 1024x768x16 &
        fluxbox &

    - name: Start VNC server (x11vnc)
      run: |
        export DISPLAY=:1
        x11vnc -display :1 -forever -nopw -shared -rfbport 5900 &

    - name: Start noVNC proxy
      run: |
        cd noVNC
        ./utils/novnc_proxy --vnc localhost:5900 --listen 6901 &

    - name: Download and start ngrok
      run: |
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        nohup ./ngrok http 6901 > ngrok.log &

    - name: Wait for services to start
      run: sleep 20

    - name: Continuously print Ngrok public URL
      run: |
        while true; do
          echo "========== NGROK TUNNELS =========="
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
          sleep 10
        done
