name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set runneradmin password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install Python (for noVNC utils)
      run: |
        Invoke-WebRequest https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe -OutFile python.exe
        Start-Process python.exe -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1" -Wait

    - name: Download and install TigerVNC
      run: |
        $url = "https://sourceforge.net/projects/tigervnc/files/stable/1.15.0/tigervnc64-1.15.0.exe/download"
        $output = "tigervnc64-1.15.0.exe"
        Invoke-WebRequest -Uri $url -OutFile $output -UseBasicParsing
        Start-Process -FilePath $output -ArgumentList "/silent" -Wait

    - name: Start TigerVNC server
      run: Start-Process -NoNewWindow -FilePath "C:\Program Files\TigerVNC\vncserver.exe" -ArgumentList ":1"

    - name: Clone and start noVNC
      run: |
        git clone https://github.com/novnc/noVNC.git
        cd noVNC
        npm install
        Start-Process -NoNewWindow -FilePath .\utils\websockify.js -ArgumentList "6901", "localhost:5901"

    - name: Sleep to let VNC and noVNC start
      run: Start-Sleep -Seconds 15

    - name: Start ngrok HTTP (noVNC) in foreground
      run: Start-Process .\ngrok\ngrok.exe -ArgumentList "http", "6901"

    - name: Loop and print Ngrok URLs forever
      run: |
        while ($true) {
          Write-Host "========== NGROK TUNNELS =========="
          $url = (Invoke-RestMethod http://127.0.0.1:4040/api/tunnels).tunnels[0].public_url
          Write-Host "URL: $url"
          Start-Sleep -Seconds 10
        }
